java:
	@javac semantics.java
	@java Main
	@rm Main.class

c++:
	@g++ semantics.cpp -o semantics.o
	@./semantics.o
	@rm semantics.o
python:
	@python3 semantics.py
haskell:
	@ghci semantics.hs
racket:
	@racket semantics.rkt